name = "TakagiFactorization"
uuid = "6ed395d4-bce0-11e8-3792-5d2702aa33ad"
authors = ["Jean-Loup Tastet <jean-loup.tastet@nbi.ku.dk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
